
LootMStatWeights = {
    [1] = {
    ITEM_MOD_STAMINA_SHORT=1,
    
    ITEM_MOD_INTELLECT_SHORT=1,
    ITEM_MOD_AGILITY_SHORT=1,
    ITEM_MOD_STRENGTH_SHORT=1,

    ITEM_MOD_CRIT_RATING_SHORT=1,
    ITEM_MOD_HASTE_RATING_SHORT=1,
    ITEM_MOD_MASTERY_RATING_SHORT=1,
    ITEM_MOD_VERSATILITY=1,
    ITEM_MOD_CR_MULTISTRIKE_SHORT=1,

    ITEM_MOD_SPIRIT_SHORT=1,
    RESISTANCE0_NAME=1, -- Armor
    
    ITEM_MOD_ATTACK_POWER_SHORT=1,
    ITEM_MOD_SPELL_POWER_SHORT=1,

    EMPTY_SOCKET_PRISMATIC=1, -- SOCKET BONUS
    ITEM_MOD_CR_STURDINESS_SHORT=1, -- INDISTRUCTABLE ?
    ITEM_MOD_CR_SPEED_SHORT=1, -- SPEED
    ITEM_MODE_CR_LIFESTEAL_SHORT=1, --LEETCH
    },

};